// src/orchestrator/state.ts — Pure reducer: applyEvent()
// No side effects. Returns new state + command list.

import type {
  OrchestratorState,
  OrchestratorEvent,
  IssueId,
  AttemptId,
  SessionId,
  RetryEntry,
  Millis,
} from "./types.js";

export type OrchestratorCommand =
  | { type: "spawn_and_run_worker";   issueId: IssueId; attemptId: AttemptId }
  | { type: "spawn_and_run_reviewer"; issueId: IssueId; attemptId: AttemptId; workerResult: import("./types.js").WorkResult }
  | { type: "schedule_retry";         issueId: IssueId; entry: RetryEntry }
  | { type: "close_session";          sessionId: SessionId; reason: string };

export function computeBackoffMs(attempt: number, maxMs: Millis): Millis {
  return Math.min(10000 * Math.pow(2, attempt - 1), maxMs as number) as Millis;
}

export function applyEvent(
  state: OrchestratorState,
  evt: OrchestratorEvent
): { state: OrchestratorState; commands: OrchestratorCommand[] } {
  const commands: OrchestratorCommand[] = [];

  switch (evt.type) {
    case "workflow.reloaded":
      state.workflow = evt.workflow;
      state.maxConcurrentAgents = evt.workflow.frontMatter.workspace.maxConcurrentAgents;
      break;

    case "linear.polled":
      for (const issue of evt.issues) {
        state.issuesById.set(issue.id, issue);
        if (!state.issueLifecycleById.has(issue.id)) {
          state.issueLifecycleById.set(issue.id, { kind: "discovered", firstSeenAt: evt.polledAt });
        }
        // Enqueue issues in "started" state
        if (issue.state.type === "started" && !state.runningIssueIds.has(issue.id)) {
          state.queuedIssueIds.add(issue.id);
        }
      }
      break;

    case "scheduler.tick":
      // 1. 促發到期的 retry
      for (const [issueId, entry] of state.retryByIssueId.entries()) {
        if (new Date(entry.nextRunAt).getTime() <= new Date(evt.now).getTime()) {
          state.queuedIssueIds.add(issueId);
          state.retryByIssueId.delete(issueId);
        }
      }
      // 2. 派發 queued issues（受 semaphore 限制）
      for (const issueId of state.queuedIssueIds) {
        if (state.runningIssueIds.size >= state.maxConcurrentAgents) break;
        if (state.runningIssueIds.has(issueId)) continue;
        commands.push({ type: "spawn_and_run_worker", issueId, attemptId: "" as AttemptId }); // AttemptId generated by command layer
      }
      break;

    case "issue.enqueue":
      state.queuedIssueIds.add(evt.issueId);
      state.issueLifecycleById.set(evt.issueId, { kind: "queued", queuedAt: evt.at, reason: evt.reason });
      break;

    case "issue.start_work": {
      state.runningIssueIds.add(evt.issueId);
      state.queuedIssueIds.delete(evt.issueId);
      const attempt = (state.attemptIdsByIssueId.get(evt.issueId) ?? []).length + 1;
      state.issueLifecycleById.set(evt.issueId, {
        kind: "running",
        sessionId: "" as SessionId, // filled by command layer
        attempt,
        startedAt: evt.at,
      });
      break;
    }

    case "worker.finished": {
      const lc = state.issueLifecycleById.get(evt.issueId);
      if (!lc || (lc.kind !== "running" && lc.kind !== "needs_changes")) break;
      state.issueLifecycleById.set(evt.issueId, {
        kind: "awaiting_review",
        sessionId: (lc as { sessionId?: SessionId }).sessionId ?? ("" as SessionId),
        attempt: (lc as { attempt?: number }).attempt ?? 1,
        workerAttemptId: evt.attemptId,
        startedAt: evt.at,
      });
      commands.push({
        type: "spawn_and_run_reviewer",
        issueId: evt.issueId,
        attemptId: "" as AttemptId,
        workerResult: evt.result,
      });
      break;
    }

    case "worker.failed":
    case "attempt.timed_out": {
      if (evt.type === "attempt.timed_out" && evt.role !== "worker") break;
      const issue = state.issuesById.get(evt.issueId);
      // Use lifecycle attempt for backoff (attemptIdsByIssueId may not be fully committed yet)
      const lc0 = state.issueLifecycleById.get(evt.issueId);
      const currentAttempt = (lc0 as { attempt?: number } | undefined)?.attempt
        ?? (state.attemptIdsByIssueId.get(evt.issueId)?.length ?? 0);
      const maxAttempts = state.workflow.frontMatter.retry.maxAttempts;

      if (!issue || currentAttempt >= maxAttempts) {
        state.issueLifecycleById.set(evt.issueId, {
          kind: "failed",
          finishedAt: evt.at,
          error: evt.type === "worker.failed"
            ? evt.error
            : { name: "TimeoutError", message: "worker timed out" },
        });
      } else {
        const nextAttempt = currentAttempt;
        const backoffMs = computeBackoffMs(nextAttempt, state.workflow.frontMatter.retry.maxRetryBackoffMs);
        const nextRunAt = new Date(Date.now() + (backoffMs as number)).toISOString() as import("./types.js").IsoDateTime;
        const entry: RetryEntry = {
          issueId: evt.issueId,
          issueKey: issue.key,
          attempt: nextAttempt,
          nextRunAt,
          backoffMs,
          reason: evt.type === "worker.failed" ? evt.error.message : "worker timeout",
        };
        state.retryByIssueId.set(evt.issueId, entry);
        state.issueLifecycleById.set(evt.issueId, {
          kind: "retry_wait",
          nextRunAt,
          attempt: nextAttempt,
          reason: entry.reason,
          backoffMs,
        });
      }
      state.runningIssueIds.delete(evt.issueId);
      break;
    }

    case "reviewer.finished": {
      if (evt.result.gate === "pass") {
        const succeededState: import("./types.js").IssueLifecycleState & { kind: "succeeded" } = {
          kind: "succeeded",
          sessionId: state.sessionIdByIssueId.get(evt.issueId) ?? ("" as SessionId),
          finishedAt: evt.at,
        };
        if (evt.result.prDraft) succeededState.pr = evt.result.prDraft;
        state.issueLifecycleById.set(evt.issueId, succeededState);
        state.runningIssueIds.delete(evt.issueId);
        const sid = state.sessionIdByIssueId.get(evt.issueId);
        if (sid) commands.push({ type: "close_session", sessionId: sid, reason: "completed" });
      } else {
        const lc = state.issueLifecycleById.get(evt.issueId);
        state.issueLifecycleById.set(evt.issueId, {
          kind: "needs_changes",
          sessionId: (lc as { sessionId?: SessionId } | undefined)?.sessionId ?? ("" as SessionId),
          attempt: (lc as { attempt?: number } | undefined)?.attempt ?? 0,
          reviewSummary: evt.result.summary,
          updatedAt: evt.at,
        });
        state.queuedIssueIds.add(evt.issueId);
        state.runningIssueIds.delete(evt.issueId);
      }
      break;
    }

    case "reviewer.failed": {
      const issue = state.issuesById.get(evt.issueId);
      const nextAttempt = (state.attemptIdsByIssueId.get(evt.issueId) ?? []).length + 1;
      const backoffMs = computeBackoffMs(nextAttempt, state.workflow.frontMatter.retry.maxRetryBackoffMs);
      const nextRunAt = new Date(Date.now() + (backoffMs as number)).toISOString() as import("./types.js").IsoDateTime;
      if (issue) {
        state.retryByIssueId.set(evt.issueId, {
          issueId: evt.issueId,
          issueKey: issue.key,
          attempt: nextAttempt,
          nextRunAt,
          backoffMs,
          reason: `reviewer failed: ${evt.error.message}`,
        });
        state.issueLifecycleById.set(evt.issueId, {
          kind: "retry_wait",
          nextRunAt,
          attempt: nextAttempt,
          reason: evt.error.message,
          backoffMs,
        });
      }
      state.runningIssueIds.delete(evt.issueId);
      break;
    }

    case "manual.retry_issue":
      state.queuedIssueIds.add(evt.issueId);
      state.retryByIssueId.delete(evt.issueId);
      state.issueLifecycleById.set(evt.issueId, { kind: "queued", queuedAt: evt.at, reason: evt.reason });
      break;

    case "manual.stop":
      state.isRunning = false;
      break;

    case "retry.due":
      // Handled by scheduler.tick — nothing to do here
      break;

    case "attempt.canceled":
      // No state transition needed — attempt is already removed from inflight
      break;
  }

  return { state, commands };
}
